import localFont from "next/font/local";
import "./globals.css";
import Footer from '@/Components/Footer'
import Header from '@/Components/Header'
import { Fredoka } from "next/font/google";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Digi-Market.com",
  description: "Generated by create next app",
};
const fredokafont=Fredoka({subsets:['latin'], weight: '700',})
export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header className={fredokafont.className} />

        {children}

        <Footer />
      </body>
    </html>
  );
}
